"""End-to-end workflow orchestration for KVOptBench benchmark artifacts."""

from __future__ import annotations

import asyncio
from pathlib import Path

from pydantic import BaseModel

from kvoptbench.analysis.summarize import summarize_results
from kvoptbench.config import validate_config
from kvoptbench.packaging.result_package import build_result_package
from kvoptbench.reports.generate import generate_report
from kvoptbench.runner.experiment import run_experiment
from kvoptbench.strategy.advisor import (
    build_strategy_advisor_report,
    write_strategy_advisor_outputs,
)


class WorkflowRunResult(BaseModel):
    """Artifacts generated by ``kvoptbench workflow run``."""

    raw_results_path: Path
    summary_path: Path
    report_path: Path
    strategy_json_path: Path
    strategy_markdown_path: Path
    package_dir: Path | None = None
    package_manifest_path: Path | None = None


def run_config_workflow(
    config_path: str | Path,
    *,
    output_dir: str | Path,
    package_dir: str | Path | None = None,
    dataset_manifest_paths: list[str | Path] | None = None,
    run_name: str | None = None,
    skip_run: bool = False,
) -> WorkflowRunResult:
    """Run one config through run, summarize, report, advisor, and packaging steps."""
    config_path = Path(config_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    config = validate_config(config_path)

    if skip_run:
        raw_results_path = config.output_file
        if not raw_results_path.exists():
            raise FileNotFoundError(
                f"Cannot skip run because raw results do not exist: {raw_results_path}"
            )
    else:
        raw_results_path = asyncio.run(run_experiment(config_path))

    summary_path = output_dir / "summary.csv"
    report_path = output_dir / "report.md"
    strategy_json_path = output_dir / "strategy_advisor.json"
    strategy_markdown_path = output_dir / "strategy_advisor.md"

    summarize_results(input_path=raw_results_path, output_path=summary_path)
    advisor = build_strategy_advisor_report(summary_path=summary_path)
    write_strategy_advisor_outputs(
        report=advisor,
        json_output_path=strategy_json_path,
        markdown_output_path=strategy_markdown_path,
    )
    generate_report(
        input_path=summary_path,
        output_path=report_path,
        strategy_input_path=strategy_json_path,
    )

    resolved_package_dir: Path | None = None
    package_manifest_path: Path | None = None
    if package_dir is not None:
        resolved_package_dir = Path(package_dir)
        package = build_result_package(
            output_dir=resolved_package_dir,
            summary_path=summary_path,
            raw_input_paths=[raw_results_path],
            workload_paths=[config.workload_file],
            dataset_manifest_paths=_dataset_manifests(config, dataset_manifest_paths),
            report_paths=[report_path, strategy_markdown_path],
            config_paths=[config_path],
            extra_artifact_paths=[strategy_json_path],
            run_name=run_name,
        )
        package_manifest_path = package.manifest_path

    return WorkflowRunResult(
        raw_results_path=raw_results_path,
        summary_path=summary_path,
        report_path=report_path,
        strategy_json_path=strategy_json_path,
        strategy_markdown_path=strategy_markdown_path,
        package_dir=resolved_package_dir,
        package_manifest_path=package_manifest_path,
    )


def _dataset_manifests(
    config,
    explicit_paths: list[str | Path] | None,
) -> list[Path]:
    paths = [Path(path) for path in explicit_paths or []]
    if paths:
        return paths
    raw_path = config.metadata.get("dataset_manifest") or config.metadata.get(
        "dataset_manifest_path"
    )
    return [Path(str(raw_path))] if raw_path else []
